language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b new https://github.com/lukmanshaikh/android_kernel_xiaomi_msm8937-2 kernel
  - cd $HOME && git clone https://github.com/lukmanshaikh/TravisCi-kernel build_kernel
  - cp $HOME/build_kernel/build.sh $HOME/kernel/build.sh
  - cd $HOME/kernel && chmod +x build.sh
  - |
    cd $HOME/kernel
    source build.sh
    make -j4 O=out
  - cp $HOME/build_kernel/zip.sh $HOME/kernel/zip.sh
  - cd $HOME/kernel && chmod +x zip.sh && source zip.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: $HOME/kernel/AnyKernel2/*.zip
  on:
    tags: false
    repo: lukmanshaikh/TravisCi-kernel
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
